"""Generate SOURCES.md — every source, its live URL, licence and last capture.

The provenance chain already exists in a domain repo: an observation carries
``source_id`` and ``raw_ref``; the manifest maps that ``raw_ref`` to the exact
URL, fetch time and content hash. Nothing surfaces it, so a reader holding a
chart or a CSV has no clickable route back to the bytes.

This writes that route out as one page. It reads only the registry, the
manifest and the health table, and it never fetches anything.
"""

from __future__ import annotations

from pathlib import Path

from . import manifest, registry

FILENAME = "SOURCES.md"


def _last_success(root: Path, source_id: str) -> dict | None:
    """Most recent manifest row that actually stored bytes."""
    best = None
    for row in manifest.iter_rows(root, source_id):
        if row.get("content_sha256") and row.get("outcome") not in {"quarantined", "failed", "skipped"}:
            if best is None or row.get("fetched_at", "") >= best.get("fetched_at", ""):
                best = row
    return best


def _health_index(root: Path) -> dict[str, dict]:
    path = Path(root) / "health" / "health.csv"
    if not path.exists():
        return {}
    import csv

    with path.open(encoding="utf-8", newline="") as fh:
        return {r["source_id"]: r for r in csv.DictReader(fh)}


def build(root: Path | str) -> str:
    root = Path(root)
    sources = sorted(registry.load_registry(root), key=lambda s: s.source_id)
    hz = _health_index(root)
    repo = root.name

    out: list[str] = [
        f"# Sources",
        "",
        f"Every source `{repo}` captures, where it comes from and what it is allowed to be",
        "used for. **Generated by `wss sources` — do not edit by hand.**",
        "",
        "Each row links to the exact URL the capture fetches. To go from a number back to",
        "its bytes: an observation carries `source_id` and `raw_ref`; the matching manifest",
        "row under `manifest/<source_id>/` holds that `raw_ref` with the URL, the fetch",
        "timestamp and a SHA-256 of exactly what came back.",
        "",
        "| source | publisher | cadence | status | last captured |",
        "| --- | --- | --- | --- | --- |",
    ]
    for s in sources:
        h = hz.get(s.source_id, {})
        last = (h.get("last_success_at") or "")[:10] or "—"
        out.append(
            f"| `{s.source_id}` | {s.publisher} | {s.cadence} | {s.status} | {last} |"
        )

    out += ["", "## Each source in full", ""]
    for s in sources:
        h = hz.get(s.source_id, {})
        cap = _last_success(root, s.source_id)
        out.append(f"### `{s.source_id}`")
        out.append("")
        out.append(f"**{s.publisher}** ({s.publisher_tier.replace('_', ' ')}) · {s.cadence} · {s.status}")
        out.append("")
        if s.notes:
            out.append(f"{s.notes.strip()}")
            out.append("")
        for ep in s.endpoints:
            out.append(f"- <{ep.url}>")
        out.append("")
        out.append(f"- **Licence / terms:** {s.licence}")
        out.append(f"- **Personal data:** {s.personal_data}")
        keeps = "no — this source destroys its own history" if s.destroys_own_history else "yes"
        out.append(f"- **Publisher keeps history:** {keeps}")
        if cap:
            sha = (cap.get("content_sha256") or "")[:12]
            out.append(
                f"- **Last stored capture:** {cap.get('fetched_at', '?')} · "
                f"`{cap.get('raw_ref', '?')}` · sha256 `{sha}…`"
            )
        else:
            out.append("- **Last stored capture:** none yet")
        if h.get("consecutive_failures", "0") not in ("", "0"):
            out.append(f"- **Consecutive failures:** {h['consecutive_failures']}")
        out.append("")

    out += [
        "## Reusing this data",
        "",
        "The captures in this repository are bytes as the publisher served them. Each",
        "source's own licence or terms of service govern reuse — they are listed per",
        "source above and they are not all the same. This repository's code is separate",
        "from the data it collects; check the source before redistributing.",
        "",
    ]
    return "\n".join(out)


def write(root: Path | str) -> Path:
    root = Path(root)
    path = root / FILENAME
    path.write_text(build(root), encoding="utf-8")
    return path
